## Occupation Stats

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from bokeh.models.formatters import BasicTickFormatter
import openpyxl as xl
# import os
# import pathlib
from pathlib import Path

import panel as pn
import hvplot.pandas
import holoviews as hv

import bokeh
import jupyter_bokeh

In [2]:
def get_filepath(curr_dir, folder, filename):
    """Returns the PosixPath path from the PosixPath under pathlib package.
    
    Args:
        curr_dir (Path): The current working directory as a PosixPath variable.
        folder (str): The folder containing the filename
        filename (str): The filename

    Returns:
        PosixPath:  Absolute path

    >>> get_filepath(Path.cwd(), "project_data/2019-29", "aggregate-economy-tables.xlsx")
    PosixPath('/Users/keshavelango/Desktop/Fall 2024/Big Data Algorithms/Project/project_data/2019-29/aggregate-economy-tables.xlsx')
    """
    path = curr_dir / folder / filename
    return path.resolve()

In [3]:
cwd = Path.cwd()
cwd

PosixPath('/Users/keshavelango/Documents/GitHub/big-data-algo/labour-latest/LabourData/notebooks')

In [4]:
path_2019_29 = "project_data/2019-29"
path_2023_33 = "project_data/2023-33"

In [5]:
occupation_filename = "occupation.xlsx"

In [6]:
occupation_filename_fn_2019 = get_filepath(cwd, path_2019_29, occupation_filename)
occupation_filename_fn_2023 = get_filepath(cwd, path_2023_33, occupation_filename)


occupation_2019_sheet = pd.ExcelFile(occupation_filename_fn_2019)
occupation_2023_sheet = pd.ExcelFile(occupation_filename_fn_2023)

In [7]:
occupation_2019_sheet_names = occupation_2019_sheet.sheet_names
occupation_2019_sheet_dfs = {}
occupation_2023_sheet_names = occupation_2023_sheet.sheet_names
occupation_2023_sheet_dfs = {}

for sheet_name in occupation_2019_sheet_names:
    occupation_2019_sheet_dfs[sheet_name] = pd.read_excel(occupation_filename_fn_2019, sheet_name=sheet_name)
for sheet_name in occupation_2023_sheet_names:
    occupation_2023_sheet_dfs[sheet_name] = pd.read_excel(occupation_filename_fn_2023, sheet_name=sheet_name)

In [8]:
occupation_2019_sheet_dfs.keys()

dict_keys(['Index', 'Table 1.1', 'Table 1.2', 'Table 1.3', 'Table 1.4', 'Table 1.5', 'Table 1.6', 'Table 1.7', 'Table 1.10', 'Table 1.11', 'Table 5.3', 'Table 5.4'])

In [9]:
occupation_2023_sheet_dfs.keys()

dict_keys(['Index', 'Table 1.1', 'Table 1.2', 'Table 1.3', 'Table 1.4', 'Table 1.5', 'Table 1.6', 'Table 1.7', 'Table 1.8', 'Table 1.9', 'Table 1.10', 'Table 1.11', 'Table 1.12'])

In [10]:
occupation_2019_sheet_dfs['Table 1.7'].columns = occupation_2019_sheet_dfs['Table 1.7'].iloc[0,:].str.strip()
occupation_2019_sheet_dfs['Table 1.7'] = occupation_2019_sheet_dfs['Table 1.7'].iloc[1:]

drop_theshold_01 = int(len(occupation_2019_sheet_dfs['Table 1.7']) * 0.01)
occupation_2019_sheet_dfs['Table 1.7'] = occupation_2019_sheet_dfs['Table 1.7'].dropna(thresh=drop_theshold_01)

occupation_2019_sheet_dfs['Table 1.7'] = occupation_2019_sheet_dfs['Table 1.7'].reset_index(drop=True)

In [11]:
occupation_2023_sheet_dfs['Table 1.2'].columns = occupation_2023_sheet_dfs['Table 1.2'].iloc[0,:].str.strip()
occupation_2023_sheet_dfs['Table 1.2'] = occupation_2023_sheet_dfs['Table 1.2'].iloc[1:]

drop_theshold_01 = int(len(occupation_2023_sheet_dfs['Table 1.2']) * 0.01)
occupation_2023_sheet_dfs['Table 1.2'] = occupation_2023_sheet_dfs['Table 1.2'].dropna(thresh=drop_theshold_01)

occupation_2023_sheet_dfs['Table 1.2'] = occupation_2023_sheet_dfs['Table 1.2'].reset_index(drop=True)

In [12]:
occupation_2019_sheet_dfs['Table 1.7'] = occupation_2019_sheet_dfs['Table 1.7'].loc[:,['2019 National Employment Matrix title', '2019 National Employment Matrix code',\
                                              'Occupation type','Employment, 2019', 'Employment change, percent, 2019-29', 'Percent self employed, 2019', \
                                                'Occupational openings, 2019-29 annual average', 'Median annual wage, 2020(1)',\
                                                      'Typical education needed for entry','Work experience in a related occupation',\
                                                          'Typical on-the-job training needed to attain competency in the occupation']]
occupation_2019_sheet_dfs['Table 1.7']

,2019 National Employment Matrix title,2019 National Employment Matrix code,Occupation type,"Employment, 2019","Employment change, percent, 2019-29","Percent self employed, 2019","Occupational openings, 2019-29 annual average","Median annual wage, 2020(1)",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation
0,"Total, all occupations",00-0000,Summary,162795.6,3.7,5.8,17454.3,41950,—,—,—
1,Management occupations,11-0000,Summary,10697.2,4.7,18.6,843,109760,—,—,—
2,Top executives,11-1000,Summary,2828,4.2,3,222.2,106180,—,—,—
3,Chief executives,11-1011,Line item,287.9,-10,24.2,13.9,185950,Bachelor's degree,5 years or more,NaN
4,General and operations managers,11-1021,Line item,2486.4,5.8,0.6,204.4,103650,Bachelor's degree,5 years or more,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1043,"Pump operators, except wellhead pumpers",53-7072,Line item,10.5,9.7,4.9,1.2,48090,High school diploma or equivalent,NaN,Moderate-term on-the-job training
1044,Wellhead pumpers,53-7073,Line item,14.1,4.2,4.9,1.5,60720,High school diploma or equivalent,Less than 5 years,Moderate-term on-the-job training
1045,Refuse and recyclable material collectors,53-7081,Line item,133.6,8.8,6.6,18.2,39100,No formal educational credential,NaN,Short-term on-the-job training
1046,"Tank car, truck, and ship loaders",53-7121,Line item,12.2,-1.7,3.7,1.3,45610,No formal educational credential,NaN,Short-term on-the-job training
1047,"Material moving workers, all other",53-7199,Line item,29.8,1.5,3.4,3.3,32850,No formal educational credential,NaN,Short-term on-the-job training

In [13]:
occupation_2023_sheet_dfs['Table 1.2'] = occupation_2023_sheet_dfs['Table 1.2'].loc[:,['2023 National Employment Matrix title', '2023 National Employment Matrix code',\
                                              'Occupation type', 'Employment, 2023', 'Employment change, percent, 2023–33', 'Percent self employed, 2023', \
                                                'Occupational openings, 2023–33 annual average', 'Median annual wage, dollars, 2023[1]',\
                                                      'Typical education needed for entry','Work experience in a related occupation',\
                                                          'Typical on-the-job training needed to attain competency in the occupation']]
occupation_2023_sheet_dfs['Table 1.2']

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry,Work experience in a related occupation,Typical on-the-job training needed to attain competency in the occupation
0,"Total, all occupations",00-0000,Summary,167849.8,4,5.8,19174.8,48060,—,—,—
1,Management occupations,11-0000,Summary,13181.3,7.3,15.1,1160,116880,—,—,—
2,Top executives,11-1000,Summary,3977.7,5.8,2.7,346.5,103460,—,—,—
3,Chief executives,11-1011,Line item,313.9,5.5,28.1,23,206680,Bachelor's degree,5 years or more,NaN
4,General and operations managers,11-1021,Line item,3630.1,5.8,0.5,320.8,101280,Bachelor's degree,5 years or more,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1108,"Pump operators, except wellhead pumpers",53-7072,Line item,11.7,5,—,1.3,54690,High school diploma or equivalent,NaN,Moderate-term on-the-job training
1109,Wellhead pumpers,53-7073,Line item,19.4,-2,—,2,71830,High school diploma or equivalent,Less than 5 years,Moderate-term on-the-job training
1110,Refuse and recyclable material collectors,53-7081,Line item,148.4,2.3,4.2,18,45760,No formal educational credential,NaN,Short-term on-the-job training
1111,"Tank car, truck, and ship loaders",53-7121,Line item,12.7,3.9,7.2,1.4,58620,No formal educational credential,NaN,Short-term on-the-job training
1112,"Material moving workers, all other",53-7199,Line item,26.5,4.4,6.8,3,40310,No formal educational credential,NaN,Short-term on-the-job training

In [16]:
occupation_2023_1_2 = occupation_2023_sheet_dfs['Table 1.2']
occupation_2019_1_7 = occupation_2019_sheet_dfs['Table 1.7']

occupation_2023_1_2.to_excel("occupation_2023_1_2.xlsx", index=False)
occupation_2019_1_7.to_excel("occupation_2019_1_7.xlsx", index=False)

In [14]:
merged_df = pd.merge(
    occupation_2023_sheet_dfs['Table 1.2'], 
    occupation_2019_sheet_dfs['Table 1.7'], 
    how='left',
    left_on=['2023 National Employment Matrix title', '2023 National Employment Matrix code','Occupation type'],
    right_on=['2019 National Employment Matrix title', '2019 National Employment Matrix code','Occupation type'],
    # suffixes=('_2023', '_2019')
)

merged_df

,2023 National Employment Matrix title,2023 National Employment Matrix code,Occupation type,"Employment, 2023","Employment change, percent, 2023–33","Percent self employed, 2023","Occupational openings, 2023–33 annual average","Median annual wage, dollars, 2023[1]",Typical education needed for entry_x,Work experience in a related occupation_x,...,2019 National Employment Matrix title,2019 National Employment Matrix code,"Employment, 2019","Employment change, percent, 2019-29","Percent self employed, 2019","Occupational openings, 2019-29 annual average","Median annual wage, 2020(1)",Typical education needed for entry_y,Work experience in a related occupation_y,Typical on-the-job training needed to attain competency in the occupation_y
0,"Total, all occupations",00-0000,Summary,167849.8,4,5.8,19174.8,48060,—,—,...,"Total, all occupations",00-0000,162795.6,3.7,5.8,17454.3,41950,—,—,—
1,Management occupations,11-0000,Summary,13181.3,7.3,15.1,1160,116880,—,—,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Top executives,11-1000,Summary,3977.7,5.8,2.7,346.5,103460,—,—,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Chief executives,11-1011,Line item,313.9,5.5,28.1,23,206680,Bachelor's degree,5 years or more,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,General and operations managers,11-1021,Line item,3630.1,5.8,0.5,320.8,101280,Bachelor's degree,5 years or more,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1108,"Pump operators, except wellhead pumpers",53-7072,Line item,11.7,5,—,1.3,54690,High school diploma or equivalent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1109,Wellhead pumpers,53-7073,Line item,19.4,-2,—,2,71830,High school diploma or equivalent,Less than 5 years,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1110,Refuse and recyclable material collectors,53-7081,Line item,148.4,2.3,4.2,18,45760,No formal educational credential,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1111,"Tank car, truck, and ship loaders",53-7121,Line item,12.7,3.9,7.2,1.4,58620,No formal educational credential,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1112,"Material moving workers, all other",53-7199,Line item,26.5,4.4,6.8,3,40310,No formal educational credential,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
import panel as pn

from pathlib import Path
import plotly.express as px
import numpy as np

import dash
from dash.dependencies import Input, Output
# import dash_core_components as dcc
# import dash_html_components as html

/var/folders/m6/39z99jrd3rq2vk51v5xvjkv80000gn/T/ipykernel_5700/1864093509.py:20: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/var/folders/m6/39z99jrd3rq2vk51v5xvjkv80000gn/T/ipykernel_5700/1864093509.py:21: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

In [53]:
# 2023 and 2029
occupation_df_2029 = pd.read_excel('project_data/2019-29/occupation.xlsx', sheet_name= "Table 1.2",skiprows=1, header=0)
occupation_df_2023 = pd.read_excel('project_data/2023-33/occupation.xlsx',sheet_name= "Table 1.2",skiprows=1, header=0)
columns_to_extract_2029 = ['2019 National Employment Matrix title', '2019 National Employment Matrix code', 'Employment, 2029','Occupational openings, 2019-29 annual average']
columns_to_extract_2023 = ['2023 National Employment Matrix title', '2023 National Employment Matrix code', 'Employment, 2023','Occupational openings, 2023–33 annual average']
occupation_df_2029 = occupation_df_2029[columns_to_extract_2029]
occupation_df_2023 = occupation_df_2023[columns_to_extract_2023]
len(occupation_df_2023), len(occupation_df_2029)

(1117, 1049)

In [54]:
occupation_df_2023.drop(occupation_df_2023.tail(4).index,inplace=True)
occupation_df_2023

,2023 National Employment Matrix title,2023 National Employment Matrix code,"Employment, 2023","Occupational openings, 2023–33 annual average"
0,"Total, all occupations",00-0000,167849.8,19174.8
1,Management occupations,11-0000,13181.3,1160.0
2,Top executives,11-1000,3977.7,346.5
3,Chief executives,11-1011,313.9,23.0
4,General and operations managers,11-1021,3630.1,320.8
...,...,...,...,...
1108,"Pump operators, except wellhead pumpers",53-7072,11.7,1.3
1109,Wellhead pumpers,53-7073,19.4,2.0
1110,Refuse and recyclable material collectors,53-7081,148.4,18.0
1111,"Tank car, truck, and ship loaders",53-7121,12.7,1.4
1112,"Material moving workers, all other",53-7199,26.5,3.0

In [58]:
# Rename columns to avoid clashes
occupation_df_2029_renamed = occupation_df_2029.rename(columns={
    '2019 National Employment Matrix title': 'occ_title',
    '2019 National Employment Matrix code': 'occ_code',
})

occupation_df_2023_renamed = occupation_df_2023.rename(columns={
    '2023 National Employment Matrix title': 'occ_title',
    '2023 National Employment Matrix code': 'occ_code',
})

occupation_df_2029_renamed.columns = occupation_df_2029_renamed.columns.str.strip()
occupation_df_2023_renamed.columns = occupation_df_2023_renamed.columns.str.strip()

common_occupation_df = pd.merge(occupation_df_2029_renamed, occupation_df_2023_renamed, 
                                on=['occ_code'], 
                                how='inner')
common_occupation_df.drop('occ_title_y',inplace=True, axis=1)
common_occupation_df.rename(columns={'occ_title_x':'occ_title'}, inplace=True)
common_occupation_df['change'] = ((common_occupation_df['Employment, 2029'] - common_occupation_df['Employment, 2023']))
common_occupation_df['percent_change'] = ((common_occupation_df['Employment, 2029'] - common_occupation_df['Employment, 2023']) / common_occupation_df['Employment, 2023']) * 10
common_occupation_df = common_occupation_df.iloc[1:,:]
common_occupation_df = common_occupation_df[~common_occupation_df['occ_code'].str.contains('-0000')]
common_occupation_df

,occ_title,occ_code,"Employment, 2029","Occupational openings, 2019-29 annual average","Employment, 2023","Occupational openings, 2023–33 annual average",change,percent_change
2,Top executives,11-1000,2946.3,222.2,3977.7,346.5,-1031.4,-2.592956
3,Chief executives,11-1011,259.1,13.9,313.9,23.0,-54.8,-1.745779
4,General and operations managers,11-1021,2630.2,204.4,3630.1,320.8,-999.9,-2.754470
5,Legislators,11-1031,57.0,3.9,33.7,2.7,23.3,6.913947
6,"Advertising, marketing, promotions, public rel...",11-2000,879.0,70.0,1112.6,94.1,-233.6,-2.099587
...,...,...,...,...,...,...,...,...
1019,"Pump operators, except wellhead pumpers",53-7072,11.5,1.2,11.7,1.3,-0.2,-0.170940
1020,Wellhead pumpers,53-7073,14.7,1.5,19.4,2.0,-4.7,-2.422680
1021,Refuse and recyclable material collectors,53-7081,145.4,18.2,148.4,18.0,-3.0,-0.202156
1022,"Tank car, truck, and ship loaders",53-7121,12.0,1.3,12.7,1.4,-0.7,-0.551181
1023,"Material moving workers, all other",53-7199,30.3,3.3,26.5,3.0,3.8,1.433962

In [63]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import pandas as pd
import plotly.express as px
import dash_bootstrap_components as dbc

# Initialize the Dash app
app = dash.Dash(__name__)

# Assuming 'common_occupation_df' is already processed and ready to use.

# Layout of the app
app.layout = html.Div([
    html.H1("Employment Change 2023 - 2029 Dashboard"),
    
    # MultiSelect for selecting job prefixes
    html.Div([
        html.Label("Select Job Prefixes"),
        dcc.Dropdown(
            id='prefix-dropdown',
            options=[{'label': str(prefix), 'value': str(prefix)} for prefix in common_occupation_df['occ_code'].str[:2].unique()],
            multi=True,
            value=['13', '43', '17', '11', '19'],  # Default values
            style={'width': '60%', 'margin': 'auto'}
        ),
    ], style={'width': '70%', 'margin': 'auto', 'padding': '20px'}),
    
    # Graphs for employment percent change
    html.Div([
        dcc.Graph(id='employment-change-graph-increase', style={'flex': '1 1 48%', 'margin': '10px'}),
        dcc.Graph(id='employment-change-graph-decrease', style={'flex': '1 1 48%', 'margin': '10px'})
    ], style={'display': 'flex', 'justify-content': 'space-between', 'width': '90%', 'margin': 'auto'})
])

# Callback to update the graphs based on selected prefixes
@app.callback(
    [
        Output('employment-change-graph-increase', 'figure'),
        Output('employment-change-graph-decrease', 'figure')
    ],
    [Input('prefix-dropdown', 'value')]
)
def update_dashboard(selected_prefixes):
    # Filter the dataframe based on the selected prefixes
    filtered_df = common_occupation_df[common_occupation_df['occ_code'].str[:2].isin(selected_prefixes)]
    
    # Top 10 jobs with the highest employment percent increase
    top5_increase = filtered_df.nlargest(10, 'percent_change')

    # Top 10 jobs with the highest employment percent decrease
    top5_decrease = filtered_df.nsmallest(10, 'percent_change')

    # Employment Change Graph - Increase
    fig_increase = px.bar(
        top5_increase,
        x='occ_title',
        y='percent_change',
        title='Top 10 Jobs with Highest Employment Increase',
        labels={'percent_change': '% Increase'},
        color_discrete_sequence=['green'],
        text='percent_change'  # Show value on bars
    )
    fig_increase.update_layout(height=400, width=600, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_increase.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    # Employment Change Graph - Decrease
    fig_decrease = px.bar(
        top5_decrease,
        x='occ_title',
        y='percent_change',
        title='Top 10 Jobs with Highest Employment Decrease',
        labels={'percent_change': '% Decrease'},
        color_discrete_sequence=['red'],
        text='percent_change'  # Show value on bars
    )
    fig_decrease.update_layout(height=400, width=600, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_decrease.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    return fig_increase, fig_decrease

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8054)

In [64]:
import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import pandas as pd
import plotly.express as px
import dash_bootstrap_components as dbc

# Initialize the Dash app
app = dash.Dash(__name__)

# Assuming 'common_occupation_df' is already processed and ready to use.

# Layout of the app
app.layout = html.Div([
    html.H1("Employment Change 2023 - 2029 Dashboard"),
    
    # MultiSelect for selecting job prefixes
    html.Div([
        html.Label("Select Job Prefixes"),
        dcc.Dropdown(
            id='prefix-dropdown',
            options=[
                {'label': f"{prefix} - {occ_title}", 'value': str(prefix)} 
                for prefix, occ_title in zip(
                    common_occupation_df['occ_code'].str[:2].unique(),
                    common_occupation_df.groupby('occ_code')['occ_title'].first()
                )
            ],
            multi=True,
            value=['13', '43', '17', '11', '19'],  # Default values
            style={'width': '80%', 'margin': 'auto'}
        ),
    ], style={'width': '80%', 'margin': 'auto', 'padding': '20px'}),
    
    # Graphs for employment percent change
    html.Div([
        dcc.Graph(id='employment-change-graph-increase', style={'flex': '1 1 48%', 'margin': '10px'}),
        dcc.Graph(id='employment-change-graph-decrease', style={'flex': '1 1 48%', 'margin': '10px'})
    ], style={'display': 'flex', 'justify-content': 'space-between', 'width': '90%', 'margin': 'auto'})
])

# Callback to update the graphs based on selected prefixes
@app.callback(
    [
        Output('employment-change-graph-increase', 'figure'),
        Output('employment-change-graph-decrease', 'figure')
    ],
    [Input('prefix-dropdown', 'value')]
)
def update_dashboard(selected_prefixes):
    # Filter the dataframe based on the selected prefixes
    filtered_df = common_occupation_df[common_occupation_df['occ_code'].str[:2].isin(selected_prefixes)]
    
    # Top 10 jobs with the highest employment percent increase
    top10_increase = filtered_df.nlargest(10, 'percent_change')

    # Top 10 jobs with the highest employment percent decrease
    top10_decrease = filtered_df.nsmallest(10, 'percent_change')

    # Employment Change Graph - Increase
    fig_increase = px.bar(
        top10_increase,
        x='occ_title',  # Display occ_title instead of occ_code
        y='percent_change',
        title='Top 10 Jobs with Highest Employment Increase',
        labels={'percent_change': '% Increase'},
        color_discrete_sequence=['green'],
        text='percent_change'  # Show value on bars
    )
    fig_increase.update_layout(height=600, width=800, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_increase.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    # Employment Change Graph - Decrease
    fig_decrease = px.bar(
        top10_decrease,
        x='occ_title',  # Display occ_title instead of occ_code
        y='percent_change',
        title='Top 10 Jobs with Highest Employment Decrease',
        labels={'percent_change': '% Decrease'},
        color_discrete_sequence=['red'],
        text='percent_change'  # Show value on bars
    )
    fig_decrease.update_layout(height=600, width=800, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_decrease.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    return fig_increase, fig_decrease

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8054)

In [ ]:
common_df = pd.merge(occupation_df_2029[columns_to_extract_2029], occupation_df_2023[columns_to_extract_2023], on=['occ_code', 'occ_title'], how='inner', suffixes=('_nat_wage_2019', '_nat_wage_2023'))
common_df.rename(columns={'tot_emp_nat_wage_2019': 'tot_emp_2019', 'tot_emp_nat_wage_2023': 'tot_emp_2023'}, inplace=True)
common_df.rename(columns={'tot_emp_nat_wage_2019': 'tot_emp_2019', 'tot_emp_nat_wage_2023': 'tot_emp_2023','a_mean_nat_wage_2019':'annual_2019','a_mean_nat_wage_2023':'annual_2023'}, inplace=True)
new_column_order = ["occ_code", "occ_title", "tot_emp_2019", "tot_emp_2023", "annual_2019", "annual_2023"]
common_df = merged_df[new_column_order]
common_df['change'] = ((common_df['tot_emp_2023'] - common_df['tot_emp_2019']))
common_df['percent_change'] = ((common_df['tot_emp_2023'] - common_df['tot_emp_2019']) / common_df['tot_emp_2019']) * 10
department_df = pd.read_excel('project_data/2023-33/skills.xlsx', sheet_name=1, skiprows=1)
department_df = department_df[:23]
departments = {row['2023 National Employment Matrix title']: row['2023 National Employment Matrix code'].split('-')[0] for _, row in department_df.iterrows()}
del departments['Total, all occupations']
departments = {key.strip(): value for key, value in departments.items()}
common_df['department_number'] = common_df['occ_code'].str.split('-').str[0].astype(str)
common_df['department_name'] = common_df['department_number'].map({v: k for k, v in departments.items()})
common_df = common_df[1:]
common_df = common_df[~common_df['occ_code'].str.contains('-0000')]
common_df

In [ ]:
nat_wage_2019 = pd.read_excel('project_data/oesm19nat/national_M2019_dl.xlsx')
columns_to_extract = ['occ_code', 'occ_title', 'tot_emp','a_mean'] 
nat_wage_2019 = nat_wage_2019[columns_to_extract]
nat_wage_2023 = pd.read_excel('project_data/oesm23nat/national_M2023_dl.xlsx')
nat_wage_2023.columns = nat_wage_2023.columns.str.lower()
columns_to_extract = ['occ_code', 'occ_title', 'tot_emp','a_mean'] 
nat_wage_2023 = nat_wage_2023[columns_to_extract]
merged_df = pd.merge(nat_wage_2019[columns_to_extract], nat_wage_2023[columns_to_extract], on=['occ_code', 'occ_title'], how='outer', suffixes=('_nat_wage_2019', '_nat_wage_2023'))
merged_df.rename(columns={'tot_emp_nat_wage_2019': 'tot_emp_2019', 'tot_emp_nat_wage_2023': 'tot_emp_2023','a_mean_nat_wage_2019':'annual_2019','a_mean_nat_wage_2023':'annual_2023'}, inplace=True)
new_column_order = ["occ_code", "occ_title", "tot_emp_2019", "tot_emp_2023", "annual_2019", "annual_2023"]
merged_df = merged_df[new_column_order]
merged_df

In [ ]:
common_df = pd.merge(nat_wage_2019[columns_to_extract], nat_wage_2023[columns_to_extract], on=['occ_code', 'occ_title'], how='inner', suffixes=('_nat_wage_2019', '_nat_wage_2023'))
common_df.rename(columns={'tot_emp_nat_wage_2019': 'tot_emp_2019', 'tot_emp_nat_wage_2023': 'tot_emp_2023'}, inplace=True)
common_df.rename(columns={'tot_emp_nat_wage_2019': 'tot_emp_2019', 'tot_emp_nat_wage_2023': 'tot_emp_2023','a_mean_nat_wage_2019':'annual_2019','a_mean_nat_wage_2023':'annual_2023'}, inplace=True)
new_column_order = ["occ_code", "occ_title", "tot_emp_2019", "tot_emp_2023", "annual_2019", "annual_2023"]
common_df = merged_df[new_column_order]
common_df['change'] = ((common_df['tot_emp_2023'] - common_df['tot_emp_2019']))
common_df['percent_change'] = ((common_df['tot_emp_2023'] - common_df['tot_emp_2019']) / common_df['tot_emp_2019']) * 10
department_df = pd.read_excel('project_data/2023-33/skills.xlsx', sheet_name=1, skiprows=1)
department_df = department_df[:23]
departments = {row['2023 National Employment Matrix title']: row['2023 National Employment Matrix code'].split('-')[0] for _, row in department_df.iterrows()}
del departments['Total, all occupations']
departments = {key.strip(): value for key, value in departments.items()}
common_df['department_number'] = common_df['occ_code'].str.split('-').str[0].astype(str)
common_df['department_name'] = common_df['department_number'].map({v: k for k, v in departments.items()})
common_df = common_df[1:]
common_df = common_df[~common_df['occ_code'].str.contains('-0000')]
common_df

In [ ]:
from dash import dcc, html

common_df['annual_2019'] = pd.to_numeric(common_df['annual_2019'], errors='coerce')
common_df['annual_2023'] = pd.to_numeric(common_df['annual_2023'], errors='coerce')

# Drop rows with missing values in both 'annual_2019' and 'annual_2023'
common_df = common_df.dropna(subset=['annual_2019', 'annual_2023'])

# Calculate the wage percent change once
common_df['wage_percent_change'] = (
    abs(common_df['annual_2023'] - common_df['annual_2019']) / common_df['annual_2019'] * 100
)

# Calculate the employment percent change if needed
common_df['percent_change'] = (
    abs(common_df['annual_2023'] - common_df['annual_2019']) / common_df['annual_2019'] * 100
)

# Initialize the Dash app
app = dash.Dash(__name__)

# Layout of the app
app.layout = html.Div([
    html.H1("Employment and Wage Change Dashboard"),
    dcc.Tabs([
        dcc.Tab(label='Total Employment Change', children=[
            html.Div([
                dcc.Dropdown(
                    id='department-dropdown-emp',
                    options=[{'label': dept, 'value': dept} for dept in common_df['department_name'].unique()],
                    value=common_df['department_name'].unique()[0],
                    clearable=False,
                    style={'width': '50%', 'margin': 'auto'}
                ),
                html.Div(id='top5-jobs-container-emp', style={
                    'display': 'flex',
                    'justify-content': 'space-between',
                    'width': '90%',
                    'margin': 'auto'
                })
            ])
        ]),
        dcc.Tab(label='Wage Change', children=[
            html.Div([
                dcc.Dropdown(
                    id='department-dropdown-wage',
                    options=[{'label': dept, 'value': dept} for dept in common_df['department_name'].unique()],
                    value=common_df['department_name'].unique()[0],
                    clearable=False,
                    style={'width': '50%', 'margin': 'auto'}
                ),
                html.Div(id='top5-jobs-container-wage', style={
                    'display': 'flex',
                    'justify-content': 'space-between',
                    'width': '90%',
                    'margin': 'auto'
                })
            ])
        ])
    ])
])

# Callback to update the employment dashboard
@app.callback(
    Output('top5-jobs-container-emp', 'children'),
    [Input('department-dropdown-emp', 'value')]
)
def update_employment_dashboard(selected_department):
    filtered_df = common_df[common_df['department_name'] == selected_department]

    # Drop duplicates based on occupation title
    filtered_df_unique = filtered_df.drop_duplicates(subset='occ_title')

    top5_increase = filtered_df_unique.nlargest(5, 'percent_change')
    top5_decrease = filtered_df_unique.nsmallest(5, 'percent_change')

    fig_increase = px.bar(
        top5_increase,
        x='occ_title',
        y='percent_change',
        title='Top 5 Jobs with Highest Employment Increase',
        labels={'percent_change': '% Increase'},
        color_discrete_sequence=['green'],
        text='percent_change'  # Adding text to the bars to show the actual value
    )
    fig_increase.update_layout(height=500, width=600, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_increase.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    fig_decrease = px.bar(
        top5_decrease,
        x='occ_title',
        y='percent_change',
        title='Top 5 Jobs with Highest Employment Decrease',
        labels={'percent_change': '% Decrease'},
        color_discrete_sequence=['red'],
        text='percent_change'  # Adding text to the bars to show the actual value
    )
    fig_decrease.update_layout(height=500, width=600, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_decrease.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    return [
        dcc.Graph(figure=fig_increase, style={'flex': '1 1 48%', 'margin': '10px'}),
        dcc.Graph(figure=fig_decrease, style={'flex': '1 1 48%', 'margin': '10px'})
    ]

# Callback to update the wage dashboard
@app.callback(
    Output('top5-jobs-container-wage', 'children'),
    [Input('department-dropdown-wage', 'value')]
)
def update_wage_dashboard(selected_department):
    filtered_df = common_df[common_df['department_name'] == selected_department]

    # Drop duplicates based on occupation title
    filtered_df_unique = filtered_df.drop_duplicates(subset='occ_title')

    top5_increase = filtered_df_unique.nlargest(5, 'wage_percent_change')
    top5_decrease = filtered_df_unique.nsmallest(5, 'wage_percent_change')

    fig_increase = px.bar(
        top5_increase,
        x='occ_title',
        y='wage_percent_change',
        title='Top 5 Jobs with Highest Wage Increase',
        labels={'wage_percent_change': '% Wage Increase'},
        color_discrete_sequence=['green'],
        text='wage_percent_change'  # Adding text to the bars to show the actual value
    )
    fig_increase.update_layout(height=400, width=600, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_increase.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    fig_decrease = px.bar(
        top5_decrease,
        x='occ_title',
        y='wage_percent_change',
        title='Top 5 Jobs with Highest Wage Decrease',
        labels={'wage_percent_change': '% Wage Decrease'},
        color_discrete_sequence=['red'],
        text='wage_percent_change'  # Adding text to the bars to show the actual value
    )
    fig_decrease.update_layout(height=400, width=600, xaxis_tickangle=-45, margin=dict(t=50, l=50, r=50, b=150))
    fig_decrease.update_traces(texttemplate='%{text:.2f}%', textposition='outside')

    return [
        dcc.Graph(figure=fig_increase, style={'flex': '1 1 50%', 'margin': '10px'}),
        dcc.Graph(figure=fig_decrease, style={'flex': '1 1 50%', 'margin': '10px'})
    ]

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True, port=8052)